#!/bin/bash

cd "$(dirname "$0")" || exit
source ../runtest_func.sh
cargo test
RUST_BACKTRACE=1

t "-1 -1 2
2 3 4 5" "YES
YES"
t "0 1 1
-2 0 4 3" "NO
YES"
t "0 0 5
-2 -2 2 1" "YES
NO"
t "0 0 2
0 0 4 4" "YES
YES"
t "0 0 5
-4 -4 4 4" "YES
YES"
