#!/bin/bash

cd "$(dirname "$0")" || exit
source ../runtest_func.sh
cargo test

t "5
3 10
1 3 7
4 10
4 1 7 3
4 3
1 2 3 2
4 4
1 2 4 2
4 10
1 1 10 10" "Case #1: 0.5
Case #2: 0.4
Case #3: 0
Case #4: 0.25
Case #5: 0.8"
