#!/bin/bash

cd "$(dirname "$0")" || exit
source ../runtest_func.sh
cargo test

RED='\033[0;31m'
NC='\033[0m'

if ! cargo build; then
    echo -e "${RED}Cargo build failed.${NC}"
    exit 1
fi

t 1000 10
t 50 0.5
t 3141 31.41
