#!/bin/bash

cd "$(dirname "$0")" || exit
source ../runtest_func.sh
cargo test

RED='\033[0;31m'
NC='\033[0m'

if ! cargo build; then
    echo -e "${RED}Cargo build failed.${NC}"
    exit 1
fi

t "5
9 6 14 1 8
2 10 3 12 11
15 13 5 7 4" 3
t "1
10
20
30" 1
t "3
1 1 1
1 1 2
2 2 2" 0
