#!/bin/bash

cd "$(dirname "$0")" || exit
source ../runtest_func.sh
cargo test
RUST_BACKTRACE=1

t "3
0 1 1 2" 7
t "0
1" 1
t "4
0 0 1 0 2" 10
t "2
0 3 1" "-1"
t "1
1 1" "-1"
t "2
0 1 3" "-1"
t "10
0 0 1 1 2 3 5 8 13 21 34" 264
