#!/bin/bash

cd "$(dirname "$0")" || exit
source ../runtest_func.sh
cargo test

RED='\033[0;31m'
NC='\033[0m'

if ! cargo build; then
    echo -e "${RED}Cargo build failed.${NC}"
    exit 1
fi

t "-1 -1
-1 2
3 2" "3 -1"
t "-60 -40
-60 -80
-20 -80" "-20 -40"
