#!/bin/bash

cd "$(dirname "$0")" || exit
source ../runtest_func.sh
cargo test

t "5
1 5
3
3 4 2" YES
t "7
1 3
4
2 4 2 7" NO
t "4
1 4
3
2 1 3" NO
t "4
1 4
3
2 4 3" NO
t "20
1 4
12
2 3 5 7 8 9 10 11 12 15 13 14" YES

