#!/bin/bash

cd "$(dirname "$0")" || exit
source ../runtest_func.sh
cargo test
RUST_BACKTRACE=1

t "4 4
1 1
4 4
..#.
..#.
.#..
.#.." 1
t "4 4
1 4
4 1
.##.
####
####
.##." -1
t "4 4
2 2
3 3
....
....
....
...." 0
