#!/bin/bash

cd $(dirname $0)
source ../runtest_func.sh
cargo test

t "100000 3
7777 AC
7777 AC
7777 AC" "1 0"

t "6 0" "0 0"

t "2 5
1 WA
1 AC
2 WA
2 AC
2 WA" "2 2"

t "2 5
1 WA
1 WA
2 WA
2 AC
2 WA" "1 1"
