#!/bin/bash

cd "$(dirname "$0")" || exit
source ../runtest_func.sh
cargo test
RUST_BACKTRACE=1

t "4 4
##..
##..
..##
..##" "possible
#...
....
....
...#"
t "4 4
###.
####
..##
..##" "possible
##..
....
...#
...#"
t "4 4
###.
##.#
..##
..##" "impossible"
t "4 4
###.
##..
..##
..##" "impossible"
t "4 4
##..
##.#
..##
..##" "impossible"
t "4 4
##..
##..
.##.
.##." "impossible"
