#!/bin/bash

cd "$(dirname "$0")" || exit
source ../runtest_func.sh
cargo test

t "happy,newyear,enjoy" "happy newyear enjoy"
t "haiku,atcoder,tasks" "haiku atcoder tasks"
t "abcde,fghihgf,edcba" "abcde fghihgf edcba"
