#!/bin/bash

cd "$(dirname "$0")" || exit
source ../runtest_func.sh
cargo test

t "3 5 10
East 7
West 3
West 11" "West 8"
t "3 3 8
West 6
East 3
East 1" 0
t "5 25 25
East 1
East 1
West 1
East 100
West 1" "East 25"

