#!/bin/bash

cd "$(dirname "$0")" || exit
source ../runtest_func.sh
cargo test
RUST_BACKTRACE=1

t "5
24 11 8 3 16" 3
t "4
5 5 5 5" 0
t "4
4 4 5 5" 0
t "3
4 4 5" 1
t "10
33 18 45 28 8 19 89 86 2 4" 5
