#!/bin/bash

cd "$(dirname "$0")" || exit
source ../runtest_func.sh
cargo test
RUST_BACKTRACE=1

t "2 3 2
..#
###" 5
t "2 3 4
..#
###" 1
t "2 2 3
##
##" 0
t "6 6 8
..##..
.#..#.
#....#
######
#....#
#....#" 208
