#!/bin/bash

cd "$(dirname "$0")" || exit
source ../runtest_func.sh
cargo test

RED='\033[0;31m'
NC='\033[0m'

if ! cargo build; then
    echo -e "${RED}Cargo build failed.${NC}"
    exit 1
fi

t "4 3 3 6 2 5 10" Takahashi
t "3 1 4 1 5 9 2" Aoki
t "1 1 1 1 1 1 1" Draw
