#!/bin/bash

cd "$(dirname "$0")" || exit
source ../runtest_func.sh
cargo test

RED='\033[0;31m'
NC='\033[0m'

if ! cargo build; then
    echo -e "${RED}Cargo build failed.${NC}"
    exit 1
fi

t "5 2
3 4 1 3 4" Yes
t "5 3
3 4 1 3 4" No
t "7 5
1 2 3 4 5 5 10" Yes
t "7 5
2 1 2 2 2 2 2" No
t "7 2
1 2 2 2 2 2 2" Yes
