#!/bin/bash

cd "$(dirname "$0")" || exit
source ../runtest_func.sh
cargo test

RED='\033[0;31m'
NC='\033[0m'

if ! cargo build; then
    echo -e "${RED}Cargo build failed.${NC}"
    exit 1
fi

t "4 3 1
1 2 3 1" 4
t "5 2 1
1 3 2 4 1" 0
t "5 1 1
1 1 1 1 1" 15
t "10 8 1
2 7 1 8 2 8 1 8 2 8" 36
