#!/bin/bash

cd "$(dirname "$0")" || exit
source ../runtest_func.sh
cargo test

t "5
5
2 2
3 1
5 2
7 1
11 1
1
17 2
2
2 2
3 1
1
2 7
1
499 10" "Case #1: 25
Case #2: 17
Case #3: 0
Case #4: 8
Case #5: 0"
