#!/bin/bash

cd "$(dirname "$0")" || exit
source ../runtest_func.sh
cargo test

RED='\033[0;31m'
NC='\033[0m'

if ! cargo build; then
    echo -e "${RED}Cargo build failed.${NC}"
    exit 1
fi

t "5
snuke
snuke
takahashi
takahashi
takahashi" takahashi
t "5
takahashi
takahashi
aoki
takahashi
snuke" takahashi
t "1
a" a
