#!/bin/bash

cd "$(dirname "$0")" || exit
source ../runtest_func.sh
cargo test

RED='\033[0;31m'
NC='\033[0m'

if ! cargo build; then
    echo -e "${RED}Cargo build failed.${NC}"
    exit 1
fi

t "7
ABC
F
BANANA
FBHC
FOXEN
CONSISTENCY
FFFB" "Case #1: 2
Case #2: 0
Case #3: 3
Case #4: 4
Case #5: 5
Case #6: 12
Case #7: 2"
