#!/bin/bash

cd "$(dirname "$0")" || exit
source ../runtest_func.sh
cargo test
RUST_BACKTRACE=1

t "4
3 4 3 2" "6 8"
t "4
1 1 1 1" "2 2"
t "4
3 1 3 2" "3 5"
t "4
4 5 3 2" "8 11"
t "5
3 4 5 3 2" "9 11"
t "5
3 4 100 3 2" "-1"
t "10
2 2 2 2 2 2 2 2 2 2" "2 3"
