#!/bin/bash

cd "$(dirname "$0")" || exit
source ../runtest_func.sh
cargo test

t "3 2
0 0 1" 1
t "1 1
0" 1
t "3 3
0 1 2" 3
t "3 2
1 1 1" 0
t "3 2
0 1 0" 2
t "7 3
0 0 1 2 0 1 0" 2
t "7 3
0 0 1 2 0 1 6" 2
