#!/bin/bash

cd "$(dirname "$0")" || exit
source ../runtest_func.sh
cargo test
RUST_BACKTRACE=1

t "2 3 3
2 2
1 1
1 3" 3
t "3 3 4
3 3
3 1
1 1
1 2" 3
t "5 5 10
2 5
4 3
2 3
5 5
2 2
5 4
5 3
5 1
3 5
1 4" 6
