#!/bin/bash

cd "$(dirname "$0")" || exit
source ../runtest_func.sh
cargo test

RED='\033[0;31m'
NC='\033[0m'

if ! cargo build; then
    echo -e "${RED}Cargo build failed.${NC}"
    exit 1
fi

t "3
tanaka taro
tanaka jiro
suzuki hanako" Yes
t "3
aaa bbb
xxx aaa
bbb yyy" No
t "2
tanaka taro
tanaka taro" No
t "3
takahashi chokudai
aoki kensho
snu ke" Yes
t "3
takahashi takahashi
aoki kensho
snu ke" Yes
