#!/bin/bash

cd "$(dirname "$0")" || exit
source ../runtest_func.sh
cargo test
export RUST_BACKTRACE=1

t "5 3
1 2
3 4
5 1" 3
t "4 10
1 2
2 1
1 2
2 1
1 2
1 3
1 4
2 3
2 4
3 4" 4
t "10 4
3 1
4 1
5 9
2 6" 3
