#!/bin/bash

cd "$(dirname "$0")" || exit
source ../runtest_func.sh
cargo test

RED='\033[0;31m'
NC='\033[0m'

if ! cargo build; then
    echo -e "${RED}Cargo build failed.${NC}"
    exit 1
fi

t "5
2 2 999 999
2 3 12 11
4 3 6 6
2 2 4 5
50 50 1 1" "Case #1: Possible
997 997
1 1
Case #2: Possible
9 1 8
1 1 1
Case #3: Possible
1 1 1
1 1 1
1 1 1
1 1 1
Case #4: Possible
2 3
1 1
Case #5: Impossible"
