#!/bin/bash

cd "$(dirname "$0")" || exit
source ../runtest_func.sh
cargo test

t "8
4 6
2 1
7 12
7 2
2 1000
4 9
4 8
4 5" "Case #1: 4 2 1 3
Case #2: 1 2
Case #3: 7 6 5 4 3 2 1
Case #4: IMPOSSIBLE
Case #5: IMPOSSIBLE
Case #6: 2 4 3 1
Case #7: 4 3 1 2
Case #8: 2 1 4 3"
