#!/bin/bash

cd "$(dirname "$0")" || exit
source ../runtest_func.sh
cargo test

t "5 5
.....
.###.
.###.
.##..
....." 6
t "5 5
.....
..#..
.###.
..#..
....." 12
t "5 5
.....
.###.
.###.
.###.
....." 4
