#!/bin/bash

cd "$(dirname "$0")" || exit
source ../runtest_func.sh
cargo test

RED='\033[0;31m'
NC='\033[0m'

if ! cargo build; then
    echo -e "${RED}Cargo build failed.${NC}"
    exit 1
fi

t "4
ooxo" 5
t "5
oxoxo" 10
t "5
ooooo" 0
t "7
xxoooxx" 16
