#!/bin/bash

cd "$(dirname "$0")" || exit
source ../runtest_func.sh
cargo test

t "january
february
march
april
may
june
july
august
september
october
november
december" 8
t "rrrrrrrrrr
srrrrrrrrr
rsr
ssr
rrs
srsrrrrrr
rssrrrrrr
sss
rrr
srr
rsrrrrrrrr
ssrrrrrrrr" 11

