#!/bin/bash

cd "$(dirname "$0")" || exit
source ../runtest_func.sh
cargo test

RED='\033[0;31m'
NC='\033[0m'

if ! cargo build; then
    echo -e "${RED}Cargo build failed.${NC}"
    exit 1
fi

t "3 3
2 1 4
3 1 3
6 4 1" Yes
t "2 4
4 3 2 1
5 6 7 8" No
