#!/bin/bash

source ../runtest_func.sh

t "6 3 4
3
1
3
2" "No
No
Yes
No
No
No"
t "6 5 4
3
1
3
2" "Yes
Yes
Yes
Yes
Yes
Yes"
t "10 13 15
3
1
4
1
5
9
2
6
5
3
5
8
9
7
9" "No
No
No
No
Yes
No
No
No
Yes
No"
