#!/bin/bash

cd "$(dirname "$0")" || exit
source ../runtest_func.sh
cargo test

RED='\033[0;31m'
NC='\033[0m'

if ! cargo build; then
    echo -e "${RED}Cargo build failed.${NC}"
    exit 1
fi

t 2 "1 2 1"
t 1 1
t 4 "1 2 1 3 1 2 1 4 1 2 1 3 1 2 1"
