#!/bin/bash

cd "$(dirname "$0")" || exit
source ../runtest_func.sh
cargo test

RED='\033[0;31m'
NC='\033[0m'

if ! cargo build; then
    echo -e "${RED}Cargo build failed.${NC}"
    exit 1
fi

t "4 2
abi
aef
bc
acg" 3
t "2 2
a
b" 0
t "5 2
abpqxyz
az
pq
bc
cy" 7
