#!/bin/bash

cd "$(dirname "$0")" || exit
source ../runtest_func.sh
cargo test

RED='\033[0;31m'
NC='\033[0m'

if ! cargo build; then
    echo -e "${RED}Cargo build failed.${NC}"
    exit 1
fi

t "4 2
1 3
2 3" Yes
t "4 3
1 2
2 3
1 3" No
t "4 3
1 4
2 4
3 4" No
