#!/bin/bash

cd "$(dirname "$0")" || exit
source ../runtest_func.sh
cargo test

RED='\033[0;31m'
NC='\033[0m'

if ! cargo build; then
    echo -e "${RED}Cargo build failed.${NC}"
    exit 1
fi

t "7 4" 0.571
t "7 3" 0.429
t "2 1" 0.500
t "10 10" 1.000
t "1 0" 0.000

