#!/bin/bash

cd "$(dirname "$0")" || exit
source ../runtest_func.sh
cargo test
RUST_BACKTRACE=1

t ". . . .
. o o .
. x x .
. . . ." ". . . .
. x x .
. o o .
. . . ."
t "o o x x
o o x x
x x o o
x x o o" "o o x x
o o x x
x x o o
x x o o"
