#!/bin/bash

cd "$(dirname "$0")" || exit
source ../runtest_func.sh
cargo test

RED='\033[0;31m'
NC='\033[0m'

if ! cargo build; then
    echo -e "${RED}Cargo build failed.${NC}"
    exit 1
fi

t "10
1 1 1 1 1 1 1 1 1 1" Yes
t "3
1 1 1" No
t "3
1 18 1" Yes
t "4
1 9 1 9" No
