#!/bin/bash

cd "$(dirname "$0")" || exit
source ../runtest_func.sh
cargo test
RUST_BACKTRACE=1

t "3
1 1
2 4
3 2" 4
t "2
1 1
1 1" 0
t "2
1 0
0 1" 2
t "3
1 0
2 0
3 0" 2
t "3
0 0
0 0
0 0" 0
t "3
0 3
0 4
0 5" 2
